version: '3'

services:
  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - D:/banco_de_dados/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    command: mongod --auth
    restart: always
